
TARGET_NO_KERNEL := true
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

USE_CAMERA_STUB := true
BOARD_USES_GENERIC_AUDIO := true

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_BOARD_PLATFORM := omap4

ENHANCED_DOMX := true

OMAP_ENHANCEMENT := true
COMMON_GLOBAL_CFLAGS += -DOMAP_ENHANCEMENT -DTARGET_OMAP4

OMAP_ENHANCEMENT_MULTIGPU := true
COMMON_GLOBAL_CFLAGS += -DOMAP_ENHANCEMENT_MULTIGPU

